dist:
  - trusty 

sudo:
  require
    
language: 
  - cpp


compiler:
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libxrandr-dev
      - libxinerama-dev
      - libxcursor-dev
      - libxi-dev
      - libxkbcommon-dev
      - libegl1-mesa-dev
      - llvm
      - lcov
      - kcov
      - cmake-data
      - cmake

before_script: |
  wget https://github.com/glfw/glfw/releases/download/3.2.1/glfw-3.2.1.zip && unzip glfw-3.2.1.zip &&
  cd glfw-3.2.1 && mkdir build && cd build && cmake .. && sudo make install && cd $TRAVIS_BUILD_DIR && git clone git://git.savannah.gnu.org/freetype/freetype2.git && cd freetype2 &&
  cmake -E make_directory build && cmake -E chdir build cmake .. && cmake --build build &&
  sudo cmake --build build --target install && cd $TRAVIS_BUILD_DIR

script:
  - cmake -DCOVERAGE=1 .
  - cmake --build .
  - ./unit_tests

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - kcov --exclude-pattern=gtest,/usr out unit_tests
  - bash <(curl -s https://codecov.io/bash) && echo "Uploaded code coverage"
